version: '3.5'
services:
  db:
    image: mongo
    ports:
      - 27000:27017
  
  jobhunterbackend:
    image: jobhunterbackend
    ports:
      - 5000:3050
    environment:
      MONGODB_SERVER: "mongodb://db:27017/Session"

  jobhuntfrontend:
    image: jobhuntfrontend
    ports:
      - 9000:80
